apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certificate.name }}
  dnsNames:
    - baylakmongush.com
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: ClusterIssuer
    group: cert-manager.io