apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.name }}
  dnsNames:
    - {{ .Values.certificate.dnsName[0] }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: ClusterIssuer
    group: cert-manager.io