apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: my-site
spec:
  secretName: tls
  dnsNames:
    - baylakmongush.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io