apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tlsCertificateName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.tlsSecretName }}
  dnsNames:
    - {{ .Values.dnsName }}
  issuerRef:
    name: {{ .Values.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io