apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: my-site
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: tls
  dnsNames:
    - baylakmongush.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io