apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-site.fullname" . }}
  labels:
    {{- include "my-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "my-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-site.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-site-creds