apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  namespace: my-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: ghcr.io/baylakmongush/baylakmongush.com:{{ .Values.image.tag }}
        ports:
          - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: my-site-creds