apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-site-ingress
  namespace: my-site
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - baylakmongush.com
      secretName: tls
  ingressClassName: nginx
  rules:
    - host: baylakmongush.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-site-service
                port:
                  name: http