apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "letsencrypt-prod.fullname" . }}
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      name: {{ .Values.acme.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            class: nginx