apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  selector:
    app: mysite
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80