apiVersion: v1
kind: Service
metadata:
  {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}