apiVersion: v1
kind: Service
metadata:
  name: my-site-service
  namespace: my-site
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: mysite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http