name: Publish and Deploy
on:
  push:
    branches:
      - master
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . -t ghcr.io/baylakmongush/baylakmongush.com:${{ github.run_number }}
          docker push ghcr.io/baylakmongush/baylakmongush.com:${{ github.run_number }}
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          exec: |
            helm upgrade --install my-site charts \
            --set image.tag=${{ github.run_number }}
